### ISSUE TITLE
password needed to import useratexample.org.pfx on macos

### ISSUE THREAD

**Issue by olivier-leduc** [mike-albano/freerad-lab#1]

**Comment by olivier-leduc** [comment]
<img width="556" alt="Screen Shot 2019-03-14 at 10 04 31 PM" src="https://user-images.githubusercontent.com/26809314/54409653-34268a80-46a5-11e9-9174-6ec7bf6ffec6.png">

**Comment by mike-albano** [comment]
Thanks for reporting. I added this to the README.
